quiz:
  model: "gemini-2.5-flash"
  temperature: 0.0
  top_p: 1.0
  n: 1
  frequency_penalty: 0.0
  max_completion_tokens: 30000
  reasoning_effort: "medium"

quiz_validator:
  model: "llama-4"
  temperature: 0.0
  top_p: 1.0
  n: 1
  frequency_penalty: 0.0
  max_completion_tokens: 8192

parser:
  upload_folder_path: "app/files"
  image_folder_path: "app/images"
  pdf_settings:
    threshold: 1.0
    max_concurrent_tasks: 5
    dpi: 300
  image_descriptor:
    model: "gemini-2.5-flash"
    temperature: 0.0
    top_p: 1.0
    n: 1
    frequency_penalty: 0.0
    max_completion_tokens: 2048

lecture_summarizer:
  model: "gemini-2.5-flash"
  temperature: 0.0
  top_p: 1.0
  n: 1
  frequency_penalty: 0.0
  max_completion_tokens: 2048
  reasoning_effort: "disable"

course_extractor: 
  upload_folder_path: "app/files"
  model: "gemini-2.5-flash"
  temperature: 0.0
  top_p: 1.0
  n: 1
  frequency_penalty: 0.0
  max_completion_tokens: 10000

exam:
  max_concurrent_tasks: 5 
  model: "gemini-2.5-flash"
  temperature: 0.0
  top_p: 1.0
  n: 1
  frequency_penalty: 0.0
  max_completion_tokens: 50000
  reasoning_effort: "medium"

litellm:
  model: "gemini-2.5-flash"
  temperature: 0.0
  top_p: 1.0
  n: 1
  frequency_penalty: 0.0
  max_completion_tokens: 10000
  reasoning_effort: "disable"
